version: "3.7"

services:
  base:
    image: internalapp-base
    build: 
      context: ./
      dockerfile: Dockerfile
  shell:
    image: nginx:1.17.3-alphine
    command: "COPY --from=base /app/dist/apps/shell /usr/share/nginx/html && COPY --from=base /app/nginx.conf  /etc/nginx/conf.d/"
    ports:
      - "4200:80"
    # volumes:
    #   - ./src:/usr/share/nginx/html
    networks:
      - microfrontend    
  dashboard:
    image: nginx:1.17.3-alphine
    command: "COPY --from=base /app/dist/apps/dashboard /usr/share/nginx/html && COPY --from=base /app/nginx.conf  /etc/nginx/conf.d/"
    ports:
      - "4201:80"
    # volumes:
    #   - ./src:/usr/share/nginx/html
    depends_on:
      - shell
    networks:
      - microfrontend    
  task-management:
    image: nginx:1.17.3-alphine
    command: "COPY --from=base /app/dist/apps/task-management /usr/share/nginx/html && COPY --from=base /app/nginx.conf  /etc/nginx/conf.d/"
    ports:
      - "4202:80"
    # volumes:
    #   - ./src:/usr/share/nginx/html
    depends_on:
      - dashboard
    networks:
      - microfrontend  

networks:
  microfrontend:
    name: microfrontend
